proStage_accueil:
    path: /
    controller: App\Controller\ProStageController::index

proStage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::affichageEntreprises

proStage_formations:
    path: /formations
    controller: App\Controller\ProStageController::affichageFormations

proStage_stages:
    path: /stage/{id}
    controller: App\Controller\ProStageController::affichageStage
