proStage_accueil:
    path: /
    controller: App\Controller\ProStageController::index

proStage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::affichageEntreprises

proStage_formations:
    path: /formations
    controller: App\Controller\ProStageController::affichageFormations

proStage_ajout_stage:
    path: /stage/ajout
    controller: App\Controller\ProStageController::ajoutStage

proStage_modif_stage:
    path: /stage/modif/{id}
    controller: App\Controller\ProStageController::modifStage

proStage_stages:
    path: /stage/{id}
    controller: App\Controller\ProStageController::affichageStage

proStage_stages_entreprise:
    path: /entreprise/{nomEntreprise}
    controller: App\Controller\ProStageController::affichageStagesParEntreprise

proStage_stages_formation:
    path: /formation/{nomFormation}
    controller: App\Controller\ProStageController::affichageStagesParFormation